# Generated by Django 4.2.3 on 2023-07-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_gaze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='followed_bodies',
            field=models.ManyToManyField(blank=True, to='galaxy_gaze.celestialbody'),
        ),
        migrations.AddField(
            model_name='user',
            name='followed_events',
            field=models.ManyToManyField(blank=True, to='galaxy_gaze.cosmicevent'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default='example@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='exampleUser', max_length=100),
        ),
    ]
