# Generated by Django 4.2.3 on 2023-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_gaze', '0002_remove_user_email_remove_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField()),
                ('object_type', models.CharField()),
                ('object_sub_type', models.CharField()),
                ('object_position', models.CharField()),
            ],
        ),
    ]
