# Generated by Django 4.2.3 on 2023-07-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_gaze', '0003_deepspaceobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmicevent',
            name='event_date',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosmicevent',
            name='event_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cosmicevent',
            name='event_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='deepspaceobject',
            name='object_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='deepspaceobject',
            name='object_position',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='deepspaceobject',
            name='object_sub_type',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='deepspaceobject',
            name='object_type',
            field=models.CharField(blank=True),
        ),
    ]
