# Generated by Django 4.2.3 on 2023-07-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy_gaze', '0004_alter_cosmicevent_event_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deepspaceobject',
            old_name='object_position',
            new_name='object_position_dec',
        ),
        migrations.AddField(
            model_name='deepspaceobject',
            name='object_position_ra',
            field=models.CharField(blank=True),
        ),
    ]
